// This file was auto-generated by RabbitCall - do not modify manually.

// ReSharper disable All

using System;
using System.Runtime.InteropServices;
using System.Security;
using System.Text;

namespace CsNamespace {
	
	public static unsafe partial class NGlobal {
		
		public static int partition2Test()        /****/ {_rc_Ciu._rc_ci();int _rc_r;_rc_PtrAndSize _rc_e;_rc_f0(&_rc_r,&_rc_e);_rc_Ciu._rc_ce(_rc_e);return _rc_r;} [SuppressUnmanagedCodeSecurity, DllImport(_rc_Ciu._rc_cl, EntryPoint = "rabbitcall_global_partition2Test")] static extern void _rc_f0(int *_rc_r,_rc_PtrAndSize *_rc_e);
	}
}
