// This file was auto-generated by RabbitCall - do not modify manually.
#pragma once

#include "rabbitcall_generated_main.h"

enum class Enum1 : int;
Enum1 parse_Enum1(const std::string &s);
std::string toString_Enum1(Enum1 v);
std::ostream & operator<<(std::ostream &os, const Enum1 &v);

enum class GpuEnum : int;
GpuEnum parse_GpuEnum(const std::string &s);
std::string toString_GpuEnum(GpuEnum v);
std::ostream & operator<<(std::ostream &os, const GpuEnum &v);

namespace CppOuterNamespace {
	enum class EnumInsideNamespace : int;
	EnumInsideNamespace parse_EnumInsideNamespace(const std::string &s);
	std::string toString_EnumInsideNamespace(EnumInsideNamespace v);
	std::ostream & operator<<(std::ostream &os, const EnumInsideNamespace &v);
}

enum NonClassEnum : int;
NonClassEnum parse_NonClassEnum(const std::string &s);
std::string toString_NonClassEnum(NonClassEnum v);
std::ostream & operator<<(std::ostream &os, const NonClassEnum &v);
